[[common-data-types]]
= Common Data Types

[#173]
== {MUST} Use common field names and semantics

There exist a variety of field types that are required in multiple
places. To achieve consistency across all API implementations, you must
use common field names and semantics whenever applicable.

[[generic-fields]]
=== Generic Fields

There are some data fields that come up again and again in API data:

* [[id]]{id}: the identity of the object. If used, IDs must be opaque strings
  and not numbers. IDs are unique within some documented context, are stable
  and don't change for a given object once assigned, and are never recycled
  cross entities.
* [[xyz_id]]{xyz_id}: an attribute within one object holding the identifier of
  another object must use a name that corresponds to the type of the referenced
  object or the relationship to the referenced object followed by `_id` (e.g.
  `partner_id` not `partner_number`, or `parent_node_id` for the reference to a parent
  node from a child node, even if both have the type `Node`).
  *Exception*: We use `customer_number` instead of `customer_id` for customer facing
  identification of customers due to legacy reasons. (Hint: `customer_id` used to be defined
  as internal only, technical integer key, see
  https://docs.google.com/document/d/1Lj56Snl6ISn6JsgyXpiRNUjzO7u2DsqBXCgHYvOQi7Y[Naming Decision: `customer_number` vs `customer_id` [internal link]]).
* [[created_at]]{created_at}: when the object was created. If used, this must
  be a `date-time` construct. Originally named [[created]]{created} before
  adding the <<235, naming conventions for date/time properties>>.
* [[modified_at]]{modified_at}: when the object was updated. If used, this must
  be a `date-time` construct. Originally named [[modified]]{modified} before
  adding the <<235, naming conventions for date/time properties>>.
* [[type]]{type}: the kind of thing this object is. If used, the type of this
  field should be a string. Types allow runtime information on the entity
  provided that otherwise requires examining the Open API file.
* [[etag]]{etag}: the <<182, ETag>> of an <<158, embedded sub-resource>>. It
  may be used to carry the {ETag} for subsequent {PUT}/{PATCH} calls (see
  <<etag-in-result-entities>>).

Example JSON schema:

[source,yaml]
----
tree_node:
  type: object
  properties:
    id:
      description: the identifier of this node
      type: string
    created_at:
      description: when got this node created
      type: string
      format: 'date-time'
    modified_at:
      description: when got this node last updated
      type: string
      format: 'date-time'
    type:
      type: string
      enum: [ 'LEAF', 'NODE' ]
    parent_node_id:
      description: the identifier of the parent node of this node
      type: string
  example:
    id: '123435'
    created: '2017-04-12T23:20:50.52Z'
    modified: '2017-04-12T23:20:50.52Z'
    type: 'LEAF'
    parent_node_id: '534321'
----

These properties are not always strictly necessary, but making them idiomatic
allows API client developers to build up a common understanding of HMCTS's
resources. There is very little utility for API consumers in having different
names or value types for these fields across APIs.

[[link-relation-fields]]
=== Link Relation Fields

To foster a consistent look and feel using simple hypertext controls for
paginating and iterating over collection values the response objects should
follow a common pattern using the below field semantics:

* [[self]]{self}:the link or cursor in a pagination response or object
  pointing to the same collection object or page.
* [[first]]{first}: the link or cursor in a pagination response or object
  pointing to the first collection object or page.
* [[prev]]{prev}: the link or cursor in a pagination response or object
  pointing to the previous collection object or page.
* [[next]]{next}: the link or cursor in a pagination response or object
  pointing to the next collection object or page.
* [[last]]{last}: the link or cursor in a pagination response or object
  pointing to the last collection object or page.

Pagination responses should contain the following additional array field to
transport the page content:

* [[items]]{items}: array of resources, holding all the items of the current
  page ({items} may be replaced by a resource name).

To simplify user experience, the applied query filters may be returned using
the following field (see also {GET-with-body}):

* [[query]]{query}: object containing the query filters applied in the search
  request to filter the collection resource.

As Result, the standard response page using <<161, pagination links>> is
defined as follows:

[source,yaml]
----
ResponsePage:
  type: object
  properties:
    self:
      description: Pagination link pointing to the current page.
      type: string
      format: uri
    first:
      description: Pagination link pointing to the first page.
      type: string
      format: uri
    prev:
      description: Pagination link pointing to the previous page.
      type: string
      format: uri
    next:
      description: Pagination link pointing to the next page.
      type: string
      format: uri
    last:
      description: Pagination link pointing to the last page.
      type: string
      format: uri

     query:
       description: >
         Object containing the query filters applied to the collection resource.
       type: object
       properties: ...

     items:
       description: Array of collection items.
       type: array
       required: false
       items:
         type: ...
----

The response page may contain additional metadata about the collection or the
current page.


[#174]
== {MUST} Follow Hypertext Control Conventions

APIs that provide hypertext controls (links) to interconnect API
resources must follow the conventions for naming and modeling of
hypertext controls as defined in section <<hypermedia>>.

[#175]
== {MUST} Use Problem JSON

http://tools.ietf.org/html/rfc7807[RFC 7807] defines the media type
`application/problem+json`. Operations should return that (together with
a suitable status code) when any problem occurred during processing and
you can give more details than the status code itself can supply,
whether it be caused by the client or the server (i.e. both for 4xx or
5xx errors).

A previous version of this guideline (before the publication of that RFC
and the registration of the media type) told to return
`application/x.problem+json` in these cases (with the same contents).
Servers for APIs defined before this change should pay attention to the
`Accept` header sent by the client and set the `Content-Type` header of
the problem response correspondingly. Clients of such APIs should accept
both media types.

APIs may define custom problems types with extension properties,
according to their specific needs.

The Open API schema definition can be found
https://hmcts.github.io/problem/schema.yaml[on github]. You can
reference it by using:

[source,yaml]
----
responses:
  503:
    description: Service Unavailable
    schema:
      $ref: 'https://hmcts.github.io/problem/schema.yaml#/Problem'
----

[#242]
== {MUST} Do not expose Stack Traces

Stack traces contain implementation details that are not part of an API,
and on which clients should never rely. Moreover, stack traces can leak
sensitive information that partners and third parties are not allowed to
receive and may disclose insights about vulnerabilities to attackers.
